### PR TITLE
#328: Support static build binaries for linux

### LINKED ISSUE #328: Provide static-linked binaries instead of dynamic ones
**Is your feature request related to a problem? Please describe.**
Currently, Go is required to be installed on the host system in order to run Pygmy.

**Describe the solution you'd like**
Pygmy should be completely standalone.  This would mean creating static-linked binaries instead of dynamic ones.

(I've got an example I can PR shortly for review)

### PR DESCRIPTION
**Pull request by fubarhouse**
Resolves #328

### CODE REVIEW

**Comment by fubarhouse** [comment]
Looking good @tobybellwood 
https://github.com/fubarhouse/pygmy-go/pull/329/checks?check_run_id=3113191539

**Comment by fubarhouse** [comment]
Now waiting for a peer review to continue this.

**Comment by tobybellwood** [comment]
Will have a deeper look, but I have some comments, whilst we're at the modifying builds stage...

The Linux/arm builds have amd64 goarch?
The Linux/386 builds could be amd64?

**Comment by fubarhouse** [comment]
Just added more, made them more explicit and consistent. Let me know what you think.

**Review by tobybellwood — APPROVED** [review]
Tested this, looks good! Thanks!!

**Pull request merged**
