### PR TITLE
Colorize Pygmy output using Aurora

### LINKED ISSUE #286: [feature] colorize output
Commands with a good/bad state should indicate their state at a glance by color, in the same way that the gem version of Pygmy does.

### PR DESCRIPTION
**Pull request by twardnw**
closes #286

### CODE REVIEW

**Comment by twardnw** [comment]
hmm, well the linter certainly isn't happy, I could not find another way to get the colors working where there were arguments provided to the `Printf`

**Comment by fubarhouse** [comment]
I can have a look tonight. 😁

**Comment by twardnw** [comment]
I should also note, I have only worked on one other project in go 😂

**Comment by fubarhouse** [comment]
I can see where it's coming from after looking at this.
I can't push to your branch, however you can see the change log here:
 - https://github.com/fubarhouse/pygmy-go/compare/issue/286?expand=1

Better yet - the commit based on yours is here:
 - https://github.com/fubarhouse/pygmy-go/commit/bd824bdc1c3cb07bda2dde7440dd1777841e1709

**Pull request merged**
